docker-mailserver:
  ssl:
    useExisting: true
    existingName: mailserver-tls-certificate
  demoMode:
    enable: true # TODO
  spfTestsDisabled: true # TODO
  domains:
    - mail.khuedoan.com
  pod:
    dockermailserver:
      override_hostname: mail.khuedoan.com
      enable_clamav: 0 # TODO need this?
      postmaster_address: postmaster@khuedoan.com
