---
apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog
  name: blog
  namespace: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: static
        - name: build
          image: alpine:latest
          workingDir: /usr/local/src
          command:
            - /bin/sh
            - -c
          args:
            - |
              apk add git hugo
              git clone --recursive https://github.com/khuedoan/blog .
              while true; do
                hugo --minify --destination /usr/share/nginx/html
                sleep 120
                git pull
              done
          volumeMounts:
            - mountPath: /usr/local/src
              name: source
            - mountPath: /usr/share/nginx/html
              name: static
      volumes:
        - name: source
          emptyDir: {}
        - name: static
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
  namespace: blog
spec:
  type: ClusterIP
  selector:
    app: blog
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: blog
spec:
  rules:
    - host: www.khuedoan.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: blog
                port:
                  name: http
