---
apiVersion: v1
kind: Namespace
metadata:
  name: homelab-docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homelab-docs
  name: homelab-docs
  namespace: homelab-docs
spec:
  selector:
    matchLabels:
      app: homelab-docs
  template:
    metadata:
      labels:
        app: homelab-docs
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: static
        - name: build
          image: alpine:latest
          workingDir: /usr/local/src
          command:
            - /bin/sh
            - -c
          args:
            - |
              apk add font-noto font-noto-emoji git graphviz make python3
              apk add --repository "http://dl-cdn.alpinelinux.org/alpine/edge/testing" mdbook
              git clone https://github.com/khuedoan/homelab .
              cd docs
              while true; do
                make diagrams
                mdbook build . --dest-dir /usr/share/nginx/html
                sleep 120
                git pull
              done
          volumeMounts:
            - mountPath: /usr/local/src
              name: source
            - mountPath: /usr/share/nginx/html
              name: static
      volumes:
        - name: source
          emptyDir: {}
        - name: static
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homelab-docs
  name: homelab-docs
  namespace: homelab-docs
spec:
  type: ClusterIP
  selector:
    app: homelab-docs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-docs
  namespace: homelab-docs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: &host homelab.khuedoan.com
      http:
        paths:
          - pathType: ImplementationSpecific
            backend:
              service:
                name: homelab-docs
                port:
                  name: http
  tls:
    - secretName: homelab-docs-tls-certificate
      hosts:
        - *host
