---
apiVersion: v1
kind: Namespace
metadata:
  name: mailserver
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mailserver.environment
  namespace: mailserver
immutable: false # TODO turn on in production
data:
  TLS_LEVEL: modern
  POSTSCREEN_ACTION: drop
  OVERRIDE_HOSTNAME: mail.khuedoan.com
  FAIL2BAN_BLOCKTYPE: drop
  POSTMASTER_ADDRESS: postmaster@khuedoan.com
  UPDATE_CHECK_INTERVAL: 10d
  POSTFIX_INET_PROTOCOLS: ipv4
  ONE_DIR: '1'
  DMS_DEBUG: '0'
  ENABLE_CLAMAV: '1'
  ENABLE_POSTGREY: '0'
  ENABLE_FAIL2BAN: '1'
  AMAVIS_LOGLEVEL: '-1'
  SPOOF_PROTECTION: '1'
  MOVE_SPAM_TO_JUNK: '1'
  ENABLE_UPDATE_CHECK: '1'
  ENABLE_SPAMASSASSIN: '1'
  SUPERVISOR_LOGLEVEL: warn
  SPAMASSASSIN_SPAM_TO_INBOX: '1'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: mailserver
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailserver
  namespace: mailserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
      annotations:
        container.apparmor.security.beta.kubernetes.io/mailserver: runtime/default
    spec:
      hostname: mail
      containers:
        - name: mailserver
          image: docker.io/mailserver/docker-mailserver:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false
            privileged: false
            capabilities:
              add:
                # file permission capabilities
                - CHOWN
                - FOWNER
                - MKNOD
                - SETGID
                - SETUID
                - DAC_OVERRIDE
                # network capabilities
                - NET_ADMIN  # needed for F2B
                - NET_RAW    # needed for F2B
                - NET_BIND_SERVICE
                # miscellaneous  capabilities
                - SYS_CHROOT
                - SYS_PTRACE
                - KILL
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
            requests:
              memory: 1Gi
              cpu: 100m
          volumeMounts:
            # - name: files
            #   subPath: postfix-accounts.cf
            #   mountPath: /tmp/docker-mailserver/postfix-accounts.cf
            #   readOnly: true
            # PVCs
            - name: data
              mountPath: /var/mail
              subPath: data
              readOnly: false
            - name: data
              mountPath: /var/mail-state
              subPath: state
              readOnly: false
            - name: data
              mountPath: /var/log/mail
              subPath: log
              readOnly: false
            # other
            - name: tmp-files
              mountPath: /tmp
              readOnly: false
          ports:
            - name: transfer
              containerPort: 25
              protocol: TCP
            - name: esmtp-implicit
              containerPort: 465
              protocol: TCP
            - name: esmtp-explicit
              containerPort: 587
            - name: imap-implicit
              containerPort: 993
              protocol: TCP
            - name: imap-explicit
              containerPort: 143
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mailserver.environment
      restartPolicy: Always
      volumes:
        # configuration files
        # - name: files
        #   configMap:
        #     name: mailserver.files
        # PVCs
        - name: data
          persistentVolumeClaim:
            claimName: data
        # other
        - name: tmp-files
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mailserver
  namespace: mailserver
  labels:
    app: mailserver
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: mailserver
  ports:
    - name: transfer
      port: 25
      targetPort: transfer
      protocol: TCP
    - name: esmtp-implicit
      port: 465
      targetPort: esmtp-implicit
      protocol: TCP
    - name: esmtp-explicit
      port: 587
      targetPort: esmtp-explicit
      protocol: TCP
    - name: imap-implicit
      port: 993
      targetPort: imap-implicit
      protocol: TCP
    - name: imap-explicit
      port: 143
      targetPort: imap-explicit
      protocol: TCP
