apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    cert-manager:
      installCRDs: true
    issuer:
      email: khuedoan98@gmail.com
